name: test_ci

packages:
  - apps/**
  - features/**
  - core/**
  - '*'

scripts:
  lint:all:
    run: melos run analyze
    description: Run all static analysis checks.

  analyze:
    run: |
      melos exec -c 1 -- \
        dart analyze . --fatal-infos
    description: |
      Run `dart analyze` in all packages.
       - Note: you can also rely on your IDEs Dart Analysis / Issues window.

command:
  bootstrap:
    usePubspecOverrides: true