name: Pull Request Lint

# triggers
on:
  pull_request:
    types: [edited, synchronize, reopened, opened]
    branches:
      - main

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  pr-lint-check:
    name: Lint Check
    runs-on: ubuntu-20.04
    timeout-minutes: 30
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
        
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          
      - name: Install Melos (monorepo cli)
        run: dart pub global activate melos
        
      - name: Install Monorepo Dependencies
        run: melos bootstrap
        
      - name: Run Dart analyzer
        uses: zgosalvez/github-actions-analyze-dart@v1
        with:
          fail-on-warnings: true
