name: Pull Request Flow

# triggers
on:
  pull_request:
    types: [ edited, synchronize, reopened, opened ]
    branches:
      - main

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  pr-check:
    name: Test & Lint Check
    runs-on: ubuntu-20.04
    timeout-minutes: 30
    
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
          cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:' # optional, change this to force refresh cache
          cache-path: '${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:' # optional, change this to specify the cache path

      - name: Install Melos (monorepo cli)
        uses: bluefireteam/melos-action@v1

      - name: Run Tests
        run: melos exec -c 6 --fail-fast --diff=origin/main...HEAD "flutter test --no-pub --coverage"

      - name: Run Analyzer
        uses: zgosalvez/github-actions-analyze-dart@v1
        with:
          fail-on-warnings: true
          
      - name: Generate Coverage
        run: melos exec -- "\$MELOS_ROOT_PATH/tools/combine_coverage.sh"

      - name: Coverage Diff
        uses: Nef10/lcov-reporter-action@v0.4.0
        with:
          lcov-file: coverage_report/lcov.info
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pr-number: ${{ github.event.number }}